export const SET_TABLE_DATA = 'SET_TABLE_DATA'
export const SET_DIALOG_ADD_ITEM = 'SET_DIALOG_ADD_ITEM'
export const SET_DIALOG_EDIT_ITEM = 'SET_DIALOG_EDIT_ITEM'
export const SET_DIALOG_DELETE_ITEM = 'SET_DIALOG_DELETE_ITEM'